// AUTO-GENERATED by scripts/gen-version.mjs (runs on `prebuild`). Do not edit by hand.
// Single-sources SDK_VERSION from package.json#version so the baked constant
// can never drift from the published version.
export const SDK_VERSION = "2.4.0";
